ACTION_NOISE_DT: 0.01
ACTION_NOISE_THETA: 0.15
BATCH_SIZE: 512
BUFFER_SIZE: 1000000
DISCOUNT: 0.975
EPS: 0.15
FIXED_OPPONENTS: false
HIDDEN_SIZES_ACTOR:
- 256
- 256
HIDDEN_SIZES_CRITIC:
- 400
- 300
- 64
K_AGAINST_STRONG: 0
LEARNING_RATE_ACTOR: 1.0e-05
LEARNING_RATE_CRITIC: 0.0001
MODEL_IDENTIFIER: ddpg
NOISE_CLIP: 0.5
NUM_EPISODES: 2000
NUM_QUANTILES: 25
POLICY_DELAY: 2
POLICY_NOISE: 0.1
START_TRAINING: 500
TAU: 0.005
TQC_TOP_K: 5
TRAINING_ROUNDS: 80
TRAIN_ITERATIONS: 6
TWIN_DELAYED: true
UPDATE_TARGET_EVERY: 10
USE_DISTRIBUTIONAL: false
USE_TARGET_NET: true
