ACTION_NOISE_DT: 0.01
ACTION_NOISE_THETA: 0.15
BATCH_SIZE: 128
BUFFER_SIZE: 1000000
DISCOUNT: 0.95
EPS: 0.1
HIDDEN_SIZES_ACTOR:
- 128
- 128
HIDDEN_SIZES_CRITIC:
- 128
- 128
- 64
LEARNING_RATE_ACTOR: 1.0e-05
LEARNING_RATE_CRITIC: 0.0001
MODEL_IDENTIFIER: ddpg
NOISE_CLIP: 0.5
NUM_EPISODES: 1000
POLICY_DELAY: 2
POLICY_NOISE: 0.0
START_TRAINING: 0
TAU: null
TRAIN_ITERATIONS: 1
TWIN_DELAYED: false
UPDATE_TARGET_EVERY: 100
USE_TARGET_NET: true
