# DDPG Configs
MODEL_IDENTIFIER: "ddpg"

NUM_EPISODES: 2000
START_TRAINING: 500
TRAINING_ROUNDS: 80
FIXED_OPPONENTS: False
K_AGAINST_STRONG: 0

EPS: 0.15
DISCOUNT: 0.975

BUFFER_SIZE: 1000000
BATCH_SIZE: 512
TRAIN_ITERATIONS: 6

# TD3 Options
TWIN_DELAYED: True
POLICY_NOISE: 0.1
NOISE_CLIP: 0.5
POLICY_DELAY: 2

LEARNING_RATE_ACTOR: 0.00001
LEARNING_RATE_CRITIC: 0.0001

HIDDEN_SIZES_ACTOR: [256, 256]
HIDDEN_SIZES_CRITIC: [400, 300, 64]

UPDATE_TARGET_EVERY: 10
USE_TARGET_NET: True
TAU: 0.005

ACTION_NOISE_THETA: 0.15
ACTION_NOISE_DT: 0.01

# Distributional / TQC options
USE_DISTRIBUTIONAL: False
NUM_QUANTILES: 25
TQC_TOP_K: 5
