# Rainbow Configs
MODEL_IDENTIFIER: "rainbow"
ACTION_FILENAME: "configs/rainbow_actions.txt"

DOUBLEQ_LEARNING: True   
DUELING: True   
NOISY: True    
PRIORITIZED_REPLAY: False 
DISTRIBUTIONAL_Q: False 
N_STEP: 7   ##

LR: 0.000125  
ADAM_BETA_1: 0.5
ADAM_BETA_2: 0.999
ADAM_EPS: 0.00015
BATCH_SIZE: 64 
GAMMA: 0.99

BUFFER_SIZE: 1000000
NUM_EPISODES: 1500   #3000 episode = 500k steps for self play num episodes= 10000 roughly 1M trans
START_TRAINING: 1000
ACTION_REPEAT: 1
TRAINING_ROUNDS: 80 
FIXED_OPPONENTS: True  ##
K_AGAINST_STRONG: 10  ##

PR_ALPHA: 0.6
PR_BETA_START: 0.4 
BETA_TARGET_REACHED: 0.9  
BETA_SCHEDULE_ACTIVE: True
PRIO_CLIP: True
PRIO_CLIP_VALUE: 0.5

N_ATOMS: 51
VMIN: -10
VMAX: 10

GRAD_CLIP: 10

EPS_START: 0.9
EPS_END: 0.01
EPS_DECAY: 0.25

SIGMA0: 0.5

TAU: 0.0005
