# Rainbow Configs
MODEL_IDENTIFIER: "rainbow"
ACTION_FILENAME: "configs/rainbow_actions.txt"

DOUBLEQ_LEARNING: False
DUELING: False
NOISY: False
PRIORITIZED_REPLAY: False
DISTRIBUTIONAL_Q: False
N_STEP: 3

LR: 0.0000625
ADAM_BETA_1: 0.9
ADAM_BETA_2: 0.999
ADAM_EPS: 0.00015
BATCH_SIZE: 32
GAMMA: 0.99

BUFFER_SIZE: 50000
NUM_EPISODES: 3000
START_TRAINING: 1
ACTION_REPEAT: 1

PR_ALPHA: 0.5
PR_BETA_START: 0.4

N_ATOMS: 51
VMIN: -10
VMAX: 10

GRAD_CLIP: 10

EPS_START: 0.9
EPS_END: 0.01
EPS_DECAY: 2500

SIGMA0: 0.5

TAU: 0.005
