# Rainbow Configs
MODEL_IDENTIFIER: "rainbow"
ACTION_FILENAME: "configs/rainbow_actions.txt"

DOUBLEQ_LEARNING: False   #
DUELING: False   #
NOISY: False
PRIORITIZED_REPLAY: True #
DISTRIBUTIONAL_Q: False
N_STEP: 1   #

LR: 0.0000625
ADAM_BETA_1: 0.9   
ADAM_BETA_2: 0.999
ADAM_EPS: 0.00015
BATCH_SIZE: 64   
GAMMA: 0.99

BUFFER_SIZE: 500000
NUM_EPISODES: 30000   #3000 episode = 500k steps
START_TRAINING: 1000
ACTION_REPEAT: 1

PR_ALPHA: 0.4   #current consideration
PR_BETA_START: 0.6  #current consideration
BETA_TARGET_REACHED: 0.9   #current consideration
BETA_SCHEDULE_ACTIVE: True
PRIO_CLIP: True
PRIO_CLIP_VALUE: 0.1

N_ATOMS: 51
VMIN: -10
VMAX: 10

GRAD_CLIP: 0.1

EPS_START: 0.9
EPS_END: 0.01
EPS_DECAY: 0.25

SIGMA0: 0.5

TAU: 0.0001   
