# TD-MPC2 Configs
MODEL_IDENTIFIER: "tdmpc2"

NUM_EPISODES: 1000
START_TRAINING: 0

Z_DIM: 256
HIDDEN_DIM: 512

LR: 0.0003
ADAM_BETA_1: 0.9
ADAM_BETA_2: 0.999
ADAM_EPS: 0.00001

CAPACITY: 1000000
PRIORITIZED: False
ALPHA: 0.6
BETA: 0.4
EPSILON: 0.000001
SEED: 42

TAU: 0.01
BATCH_SIZE: 256
TRAIN_HORIZON: 12
LAMBDA_W: 0.9
GRAD_CLIP: 10.0

PI_LR: 0.0003

MPC_SAMPLES: 512
MPC_ITERS: 3
MPC_SIGMA: 0.4
MPC_TEMP: 1.0
GAMMA: 0.99
EXPL_NOISE: 0.1
